### ISSUE TITLE
Error start

### ISSUE THREAD

**Issue by S1ROZHA** [tejado/telegram-nearby-map#1]
i`m ready installed all dependencies in 'npm i' and use npm start then have error
![image](https://user-images.githubusercontent.com/20708709/108253020-fc160500-7161-11eb-8ab4-6adfc854d878.png)

**Comment by quibie** [comment]
from the initial 'npm i' command i received errors for missing python + 'c++ building tools'.
After getting python3.9 and 'visual studio Build Tools' the error is gone.

**Comment by tejado** [comment]
Thanks for the info @quibie 
I will add it to the readme.

**Comment by S1ROZHA** [comment]
> from the initial 'npm i' command i received errors for missing python and 'c++ building tools'.
> After getting python3.9 and 'visual studio Build Tools' the error is gone.

did not help
