### ISSUE TITLE
Erros in NPM start

### ISSUE THREAD

**Issue by meetgyn** [tejado/telegram-nearby-map#13]
I did any correct procedure, but when Start the NPM is giving this error. I already made the installations of the TDLT dependencies 

I'm using Debian 11 
Even I have a system that uses NPM and it is working properly. 

![image](https://user-images.githubusercontent.com/3695608/145585563-c35f1e8d-96bd-4a85-85df-b1be0666e56c.png)

**Comment by ayovotesolo** [comment]
edit package.json and use "npx parcel build ...."

**Comment by tejado** [comment]
@meetgyn would be great if you can provide feedback if the hint from ayovotesolo worked for you. Thanks!

**Comment by youctyu** [comment]
npm install --save-dev parcel-bundler，use ubuntu20.04，can success npm start

**Comment by tejado** [comment]
Should be resolved now. Please check!
