### ISSUE TITLE
success in npm start, but can't load maps

### ISSUE THREAD

**Issue by ayovotesolo** [tejado/telegram-nearby-map#14]
success in npm start, but can't load maps.. cant you solve it?

https://tele-map-solo.herokuapp.com/

in heroku console, there is message "Please enter phone number:" but i can't input phone number

**Comment by tejado** [comment]
Hi @ayovotesolo 
but currently you have to :-) this is step 6: "Look carefully at the output: you will need to confirm your Telegram login".
There might be options offered by tdlib to do this without the console, but they are not yet implemented in telegram-nearby-map. Feel free to provide a PR for it. A good starting point could be https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_authentication_phone_number.html

**Comment by Hanar1988** [comment]
Hi Everyone, my issue is when i load 127.0.0.1:3000 React page popup "Edit src/App.js and save to reload"
Note: am using kali linux
