### ISSUE TITLE
Possibility to output User ID and Lat Lng?

### ISSUE THREAD

**Issue by jjones3286** [tejado/telegram-nearby-map#16]
Hi there! I absolutely love this tool and I have been showcasing it during various OSINT demos. 

Is there a possibility to output the User ID and their associated geolocations, perhaps to a CSV? The reason I'm asking is because I think having this data and then using a third party application to triangulate users that appear across multiple locations would be hugely beneficial. I have tried implementing a few tweaks to the script to see if I can do it myself, but I have had no luck.

Again, fantastic work with this utility! It is fantastic!

**Comment by tejado** [comment]
Hi,

yes of course. This can be implemented. What did you tried so far? :)
And what additional trilateration would you expect or would like to do outside this tool? It seems the current integrated trilateration has some issues and it also does not show any "moving" users which would be even better.

**Comment by jjones3286** [comment]
Hi! Thanks so much for replying!

So far, not that very much in all honesty - I have tried using the native write to file function, but no joy. 

What I am looking to do is write an OSINT workflow article which focuses on the tool you have developed and to use the outputs on system such as Google Earth in order to show manual techniques that can be applied to triangulate users, roughly in line with this article: https://ipfiles.wordpress.com/2014/08/31/cellular-triangulation/.

But, I am also very sure that the capability to output results would be a HUGE hit for other users - I have been showcasing this tool to various Law Enforcement, their jaws hit the floor every time they see it. But I agree, the idea of "moving" users is very appealing too. I see a lot of potential for this tool.

**Comment by SupremoIntra** [comment]
HI! Are there any news about the possibility to output User ID and latitude/longitude? Now i'm taking data directly from bot.log file but i know this isn't the best method. Any ideas?
