### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by FoIsBo** [tejado/telegram-nearby-map#17]
I have the next problem:
![image](https://user-images.githubusercontent.com/74991842/150157140-b4cf0f08-5f01-4b97-9f29-fca5e1839601.png)

How to solve it?

**Comment by RunningTarg3t** [comment]
I installed it yesterday (Windows10) and get the same problem. I see the webinterface without results. Dont know why.

**Comment by cybrcr** [comment]
i have the same error (also Windows 10)

**Comment by tejado** [comment]
Hi all,

if you repeat the start of the telegram-nearby-map with "npm start", you get the error again? So basically you get it everytime if you start the program?

**Comment by FoIsBo** [comment]
> Hi all,
> 
> if you repeat the start of the telegram-nearby-map with "npm start", you get the error again? So basically you get it everytime if you start the program?

Yes every time the same problem.

**Comment by cybrcr** [comment]
yes. its a clean intall. everytime i start, he ask me to confirm my number. i enter my mobilenumber and receive the security code. after enter that code, i get that message and the program is closed.

**Comment by Alb-310** [comment]
Same error when I have to enter the auth code :
``[ 1][t 2][1644275620.771245479][MessageContent.cpp:3846][#1][!Td]	Receive without authorization messageMediaEmpty {
}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
``

**Comment by raftopoulos-xrhstos** [comment]
Hello, for me (Windows11) new tdlib libraries are fixing this issue! Thank you!

**Comment by tejado** [comment]
Great - thank you! 

@FoIsBo @cybrcr @RunningTarg3t  what about you?
