### ISSUE TITLE
Cant Open db.sqlite f

### ISSUE THREAD

**Issue by cybermonitorr** [tejado/telegram-nearby-map#19]
hello sir thanks for sharing this great script but i have a problem when i want to open db.sqlite file witch suppose to find User ID and Location in , it says its not database file , i tried sqlite browser 

Thanks a lot

**Comment by dd121** [comment]
its encrypted

**Comment by cybermonitorr** [comment]
> its encrypted

Then how to decrypt it bro ? any idea ?

**Comment by tejado** [comment]
This issue is related to the TDlib dependency and not this project itself. Please see https://github.com/tdlib/td/issues/1454

**Comment by cybermonitorr** [comment]
Thanks bro
