### ISSUE TITLE
Database dosenot opem 

### ISSUE THREAD

**Issue by cybermonitorr** [tejado/telegram-nearby-map#2]
hello man could you tell us how can we open the database ?

**Comment by tejado** [comment]
Hi, what do you mean? The database will be automatically created by the telegram library.

**Comment by cybermonitorr** [comment]
yeah i know it create by telegram but then can i open the database with sqlite viewer or something like that ?

**Comment by tejado** [comment]
This is the wrong place - you need to check out the tdlib if you can open the database: https://core.telegram.org/tdlib
