### ISSUE TITLE
2 Errors 

### ISSUE THREAD

**Issue by adlen209** [tejado/telegram-nearby-map#23]
Hi :-)

I get this errors while launching the app : 

1) node:55470) UnhandledPromiseRejectionWarning: #<Object> 

2) TypeError: Cannot read property 'users_nearby' of null

Can someone help me please ?

![Screenshot_2022-03-01_17-21-57](https://user-images.githubusercontent.com/43779866/156266166-a2b37eea-d451-4af0-8f17-aa4c89bddee5.png)

**Comment by tejado** [comment]
Hi @adlen209 
I updates the linux tdlib.native dependency. Can you try again please?

**Comment by fs0ciety0010101** [comment]
![1](https://user-images.githubusercontent.com/105839487/169214177-d5d3ecd5-ec70-4ce1-9512-d05af82505d9.jpg)
Another one Error. I can't resolve it. Can you help me please?

**Comment by CreeperXP** [comment]
> ![1](https://user-images.githubusercontent.com/105839487/169214177-d5d3ecd5-ec70-4ce1-9512-d05af82505d9.jpg) Another one Error. I can't resolve it. Can you help me please?

try manually update tdlib
https://github.com/ForNeVeR/tdlib.native/releases

**Comment by tejado** [comment]
Should be resolved now. Please check!
