### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Bafomet666** [tejado/telegram-nearby-map#29]
┌─[✗]─[apashe@apashe]─[~/Desktop/telegram-nearby-map-main]
└──╼ $npm start

> start
> npm run buildParcel && npm run startServer

> buildParcel
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

🚨 Build failed.

@parcel/optimizer-terser: Unexpected token: punc (()

  /home/apashe/Desktop/telegram-nearby-map-main/node_modules/ol/src/proj.js:328:4
    327 |      */
  > 328 |     function (input, opt_output, opt_dimension) {
  >     |    ^ Unexpected token: punc (()
    329 |       const length = input.length;
    330 |       const dimension = opt_dimension !== undefined ? opt_dimension : 2;

  💡 It's likely that Terser doesn't support this syntax yet.

npm ERR! code 1
npm ERR! path /home/apashe/Desktop/telegram-nearby-map-main
npm ERR! command failed
npm ERR! command sh -c parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apashe/.npm/_logs/2022-03-24T23_01_47_824Z-debug.log
npm ERR! code 1
npm ERR! path /home/apashe/Desktop/telegram-nearby-map-main
npm ERR! command failed
npm ERR! command sh -c npm run buildParcel && npm run startServer

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apashe/.npm/_logs/2022-03-24T23_01_47_839Z-debug.log

**Comment by DaniilGen** [comment]
Same problem

**Comment by tejado** [comment]
Should be resolved now. Please check!
