### ISSUE TITLE
Handshake is not yet ready

### ISSUE THREAD

**Issue by V1lu0** [tejado/telegram-nearby-map#3]
Listening at http://127.0.0.1:3000
[ 2][t 5][1629098971.683029174][Timer.cpp:67][#1][!Td][&duration > max_duration_]       SLOW: [name:change key][duration:5154.9us]
[ 2][t 5][1629098971.683246850][TdDb.cpp:323][#1][!Td]  Got PRAGMA user_version = 13
[ 2][t 5][1629098971.686511278][AuthDataShared.cpp:109][#1][!Td]        DcId{1} [auth_key_id:0][state:Empty][created_at:0.000000]
[ 2][t 5][1629098971.687593221][Session.cpp:167][#1][!SessionProxy:1:main]      Generate new session_id 466704***********286006 for auth key 0 for main DC1
Please enter phone number: [ 2][t 3][1629098973.598073482][Session.cpp:1274][#1][!Session:1:main::HandshakeActor]       Failed to open connection: [Error : 10054 : Error on [fd:00000000000003FC] : [149.154.175.50:443] to DcId{1} from [0.0.0.0:51632]]
[ 2][t 5][1629098973.598258018][Session.cpp:1207][#1][!Session:1:main]  Handshake is not yet ready

**Comment by V1lu0** [comment]
I used a global VPN but still.

**Comment by tejado** [comment]
Hi,
thanks for creating this issue. I will have a look on it as I did not used the app sice few months. Maybe I have to update some dependencies.

**Comment by V1lu0** [comment]
Looking forward to your fixes

**Comment by V1lu0** [comment]
Would you tell me what version number of your node.js. My node.js version number is v12.19.0. Thank you.

**Comment by GuoYuefei** [comment]
我也有这个问题，这是网路原因吗

**Comment by tejado** [comment]
As the problem occurs in the tdlib, it makes sense to look at the tdlib issue page, e.g. following could help you: https://github.com/tdlib/td/issues/730
