### ISSUE TITLE
Error Cannot GET/ in url 127.0.0.1:3000

### ISSUE THREAD

**Issue by Serg95off** [tejado/telegram-nearby-map#30]
help me please, 
![Снимок1](https://user-images.githubusercontent.com/20522447/160242173-be50e1cb-f145-4b3b-91b2-a7dad385c8a6.PNG)
![Снимок2](https://user-images.githubusercontent.com/20522447/160242174-81092826-ae98-4ac2-9393-51ff3e6c1ee7.PNG)
session opens in mobile app. session name Unknown device nameApp 1.0, TDlib 1.8.2
local site not working =(
what am I doing wrong?

**Comment by tejado** [comment]
Should be resolved now. Please check!
