### ISSUE TITLE
TDLib Error?

### ISSUE THREAD

**Issue by jjones3286** [tejado/telegram-nearby-map#31]
Hi! I have just recently tried to run the tool.

The following error was noted in the CLI:

Current WD: d:\Scripts\nodejs\telegram-nearby-map-new\lib\tdlib
Lib Path: tdjson.dll
Listening at http://127.0.0.1:3000
[ 2][t 5][1648985902.399612665][Timer.cpp:67][#1][!Td][&duration > max_duration_]       SLOW: [name:change key][duration:2470.9us]
[ 2][t 5][1648985902.399803400][TdDb.cpp:323][#1][!Td]  Got PRAGMA user_version = 13
[ 2][t 5][1648985902.403828620][AuthDataShared.cpp:109][#1][!Td]        DcId{4} [auth_key_id:1234567890][state:OK][created_at:1641170601.000000]
[ 2][t 5][1648985902.406669616][Session.cpp:167][#1][!SessionProxy:4:main]      Generate new session_id 14629334249756723973 for auth key 1234567890 for main DC4
[ 0][t 5][1648985902.775906324][MessagesManager.cpp:5601][#1][!Td]      Check `have_dialog(dialog_id)` failed

It looks to me like the tdlib needs updating. I tried running a fresh install of the latest version of the tool but it kept throwing up lots of different errors. 

Can you advise on a fix?

**Comment by tejado** [comment]
Should be resolved now. Please check!
