### ISSUE TITLE
how send Message to them ?

### ISSUE THREAD

**Issue by MrPWH** [tejado/telegram-nearby-map#35]
hello !
i cant connect to any body with api 
how connect to them with id 
i have not username for connection
i need send msg to users find

**Comment by imakealol** [comment]
you must only edit the config.example.json

var config = {}


// your telegram API credentials
// please go to https://my.telegram.org to create your API credentials
config.telegramApiId = 123456789;
config.telegramApiHash = '';

enter the bot data and save the file as config.js

that's it. After running this with npm start it should work

**Comment by tejado** [comment]
There is no functionality in the UI to message them.
