### ISSUE TITLE
Error while reading RSA public key

### ISSUE THREAD

**Issue by frech87** [tejado/telegram-nearby-map#37]
Hi. Great job. When npm start, return message [Error : 0 : Error while reading RSA public key] and after Aborted (core dumped)

**Comment by frech87** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/50770138/172848673-456c9977-cf1e-430b-9a28-7c049c91ed54.jpg)

**Comment by imakealol** [comment]
Try this https://github.com/imakealol/telegram-nearby-map-reup-working and let me know if works. :) I think it is better you start it as user, not as root.

**Comment by tejado** [comment]
@imakealol 
no fork, no visible overview about the changes to my code base-> it looks like scam. Comment removed.

**Comment by tejado** [comment]
Should be resolved now. Please check!
