### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "ol/ol.css". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by SupremoIntra** [tejado/telegram-nearby-map#39]
Uncaught TypeError: Failed to resolve module specifier "ol/ol.css". Relative references must start with either "/", "./", or "../".

Which should be the problem?

**Comment by tejado** [comment]
What npm version are you using and what is the output of npm install?

**Comment by imakealol** [comment]
Try this https://github.com/imakealol/telegram-nearby-map-reup-working and let me know if works. :)

**Comment by tejado** [comment]
@imakealol 
no fork, no visible overview about the changes to my code base-> it looks like scam. Comment removed.

**Comment by tejado** [comment]
Should be resolved now. Please check!
