### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by jaxongir-kaxarov** [tejado/telegram-nearby-map#45]
Error: Request failed with status code 500
![Screenshot from 2022-10-23 21-43-15](https://user-images.githubusercontent.com/112774958/197404783-994fb67c-1620-4ac5-8674-0d10fd474ba1.png)

**Comment by imakealol** [comment]
Try this https://github.com/imakealol/telegram-nearby-map-reup-working and let me know if works. :)

**Comment by tejado** [comment]
@imakealol 
no fork, no visible overview about the changes to my code base-> it looks like scam. Comment removed.

**Comment by tejado** [comment]
Should be resolved now. Please check!
