### ISSUE TITLE
Showing build failed error!

### ISSUE THREAD

**Issue by Ysr-kmr** [tejado/telegram-nearby-map#46]
@parcel/optimizer-terser: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
![Screenshot_20221024_045442](https://user-images.githubusercontent.com/111630090/197488850-c37b5706-7c85-44ae-a1ea-acdba884e61c.png)

**Comment by imakealol** [comment]
Try this https://github.com/imakealol/telegram-nearby-map-reup-working and let me know if works. :)

**Comment by tejado** [comment]
@imakealol 
no fork, no visible overview about the changes to my code base-> it looks like scam. Comment removed.

**Comment by onoakino** [comment]
I am also getting this error. What can we do to work around this issue?

**Comment by snowriver1314** [comment]
> @parcel/optimizer-terser: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer ![Screenshot_20221024_045442](https://user-images.githubusercontent.com/111630090/197488850-c37b5706-7c85-44ae-a1ea-acdba884e61c.png)

You should change your version of node.js to 7.x.

**Comment by jonface** [comment]
https://github.com/parcel-bundler/parcel/issues/8005#issuecomment-1120149358

Workaround here.

**Comment by tejado** [comment]
Should be resolved now. Please check!
