### ISSUE TITLE
Getting error when running npm start

### ISSUE THREAD

**Issue by onoakino** [tejado/telegram-nearby-map#47]
start
> npm run buildParcel && npm run startServer

> buildParcel
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

error: unknown option `--dist-dir'
npm ERR! code 1
npm ERR! path /home/bro/telegram-nearby-map
npm ERR! command failed
npm ERR! command sh -c parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bro/.npm/_logs/2022-11-02T20_38_03_307Z-debug.log
npm ERR! code 1
npm ERR! path /home/bro/telegram-nearby-map
npm ERR! command failed
npm ERR! command sh -c npm run buildParcel && npm run startServer

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bro/.npm/_logs/2022-11-02T20_38_03_360Z-debug.log

--------- the contents of the /home/bro/.npm/_logs/2022-11-02T20_38_03_360Z-debug.log i pasted below

0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'buildParcel' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/bro/telegram-nearby-map/.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/bro/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 18ms
19 verbose npm-session 10df51d7e89ee590
20 timing npm:load Completed in 34ms
21 timing command:run-script Completed in 243ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose cwd /home/bro/telegram-nearby-map
24 verbose Linux 5.10.0-16-amd64
25 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "buildParcel"
26 verbose node v12.22.12
27 verbose npm  v7.5.2
28 error code 1
29 error path /home/bro/telegram-nearby-map
30 error command failed
31 error command sh -c parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/
32 verbose exit 1

**Comment by imakealol** [comment]
Try this https://github.com/imakealol/telegram-nearby-map-reup-working and let me know if works. :)

**Comment by tejado** [comment]
@imakealol 
no fork, no visible overview about the changes to my code base-> it looks like scam. Comment removed.

**Comment by imakealol** [comment]
sorry no, i didn't want that. It wasn't intentional, I just meant it well. I gave you all credits. Should I fork this again or what should I do?

**Comment by tejado** [comment]
> sorry no, i didn't want that. It wasn't intentional, I just meant it well. I gave you all credits. Should I fork this again or what should I do?

If you did not change anything in your repo, what is then the reason anyone should use it?

At general:
A fork would be much better, so that the changes between this repository and yours are clearly visible. If you fork it outside of github, don't rewrite the complete repo history.
Additionally, if you would like to support this project, a fix (-> pull request) to this repository is also appreciated.

**Comment by imakealol** [comment]
Ich sehe grad. Du kommst aus deutschland. Nein wirklich, das war echt nicht so gemeint. Ich hab noch eine funktionierende Version auf mein Server gehabt. Das einzigste was ich gemacht habe ist ein reup. Das einzigste was dabei hinzu gekommen ist, sind die npm module. Ich hab mir gedacht, somit tue ich allen ein Gefallen. Vielleicht findest du so schneller den Fehler. Das war meine einzigste Intension dabei.

**Comment by tejado** [comment]
@imakealol 
I rather stick to english so it is understandable for everyone. Feel free to write me a mail.

Anyway: I provided you guidance how to approach this in a better way. Also node_modules are npm dependencies and should not be part of the repository. If the dependencies are outdated, package.json needs to be fixed.

**Comment by imakealol** [comment]
ok i'm sorry.

**Comment by tejado** [comment]
> ok i'm sorry. Should I delete it completely now, or is it okay if I leave it like that?

Don't be sorry if you learn from it and make it better in the future. Try my suggestions and provide a proper fix over a PR.

**Comment by onoakino** [comment]
Sorry, but I would like to follow-up on this issue.

**Comment by SuLLLivaN** [comment]
I had too such problem, but solve it with installation of nodejs 17.4

**Comment by onoakino** [comment]
Thank you, @SuLLLivaN. Updating it to node 17.x made me get past that error. Closing this issue now.
