### ISSUE TITLE
Segmentation fault: 11  npm run startServer

### ISSUE THREAD

**Issue by kulikovdmitr** [tejado/telegram-nearby-map#48]
Hello dear author, could you look at this error,?
I would like to know if your server startup is working

```
@MacBook-Pro-8 ~/m/telegram-nearby-map (main) [1]> npm start

> start
> npm run buildParcel && npm run startServer


> buildParcel
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

✨ Built in 142ms

web-build/index.html              1.55 KB    270ms
web-build/index.a2c0f328.css      8.71 KB     52ms
web-build/index.152cb747.js     386.04 KB    2.57s

> startServer
> node server.js

Current WD: /Users/dvkulikov/map/telegram-nearby-map/lib/tdlib
Lib Path: ./libtdjson.dylib
sh: line 1: 59701 Segmentation fault: 11  npm run startServer
```

Node & Npm versions

```
@MacBook-Pro-8 ~/m/telegram-nearby-map (main) [SIGSEGV]> node -v
v19.3.0
@MacBook-Pro-8 ~/m/telegram-nearby-map (main)> npm -v
9.2.0
@MacBook-Pro-8 ~/m/telegram-nearby-map (main)> 
```

**Comment by PheeZz** [comment]
Same error @kulikovdmitr (you can answer at your own language, or go to my profile, telegram link there, if you have some problems with english)

Do you fix this error?

```
Current WD: /home/pheezz/telegram-nearby-map/lib/tdlib
Lib Path: ./libtdjson.so
[1]    19475 segmentation fault (core dumped)  npm start
```

![image](https://user-images.githubusercontent.com/53043573/225031489-274641a9-b0ff-4288-bf03-d397e2bc7f33.png)

**Comment by kulikovdmitr** [comment]
> Same error @kulikovdmitr (you can answer at your own language, or go to my profile, telegram link there, if you have some problems with english)
> 
> Do you fix this error?
> 
> ```
> Current WD: /home/pheezz/telegram-nearby-map/lib/tdlib
> Lib Path: ./libtdjson.so
> [1]    19475 segmentation fault (core dumped)  npm start
> ```
> 
> ![image](https://user-images.githubusercontent.com/53043573/225031489-274641a9-b0ff-4288-bf03-d397e2bc7f33.png)

Hi @PheeZz, unfortunately I couldn't solve this problem.. :(

**Comment by tejado** [comment]
Should be resolved now. - Can you please check?
