### ISSUE TITLE
Incompatible with MacOS?

### ISSUE THREAD

**Issue by aquaticexpectency** [tejado/telegram-nearby-map#53]
I'm running the program, but the output says `Error: Dynamic Loading Error: dlopen(./libtdjson.dylib, 0x0005): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
`
and then says errors like "no such file" "no such file, not in dyld cache"
if can't, can i just delete the folder to clear the dependencies?

**Comment by tejado** [comment]
Switched to prebuild-tdlib - should now work with macOS.
