### ISSUE TITLE
failed to resolve 'ol/ol.css' from './web-src/web.js'

### ISSUE THREAD

**Issue by sedfsdfsdasdasdf** [tejado/telegram-nearby-map#9]
hello, i have this problem:
> start
> npm run buildParcel && npm run startServer

> buildParcel
> parcel build ./web-src/index.html --public-url / --dist-dir ./web-build/

× Build failed.

@parcel/core: Failed to resolve 'ol/ol.css' from './web-src/web.js'

  C:\Users\MYUSERPRIVATEXD(changed now)\Downloads\telegram-nearby-map-main\telegram-nearby-map-main\web-src\web.js:1:8
  > 1 | import 'ol/ol.css';
  >   |        ^^^^^^^^^^^
    2 | import Map from 'ol/Map';
    3 | import Overlay from 'ol/Overlay';

**Comment by tejado** [comment]
Hi,

any info how you resolved it? Issue #10 seems to be the same from a different user.
What node version did you use?
